table Solution2
	lineageTag: d6c8fb9e-baab-4b81-8aa0-3ef718e86292

	column Column1
		dataType: string
		lineageTag: eebce761-9313-4232-b440-91e54ee492e3
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 6a4489e5-e13e-42af-997d-557b53b0b1a5
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Solution2 = m
		mode: import
		source = ```
				let
				    Source = Raw,
				    DistinctGroups = 
				        List.Distinct ( Source[Group] ),
				    Transformation = 
				        List.Transform (
				            DistinctGroups,
				            ( x ) =>
				                let
				                    T         = Table.SelectRows ( Source, each [Group] = x ),
				                    EmpIDName = Table.ToRows ( T[[Emp ID], [Name]] ),
				                    Result    = Table.FromRows ( { { T[Group]{0}, T[Dept]{0} } } & EmpIDName )
				                in
				                    Result
				        ),
				    CombineTables = 
				        Table.Combine ( Transformation )
				in
				    CombineTables
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

