table Solution1
	lineageTag: 9701988a-fa84-4b70-85de-6f2059f18cab

	column Subjects
		dataType: string
		lineageTag: 10cde85e-6e59-4227-9413-ff068bc7feda
		summarizeBy: none
		sourceColumn: Subjects

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: eb592f2a-d8f1-4e9b-acc5-7f7cef81ccfa
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition Solution1 = m
		mode: import
		source = ```
				let
				    Source = Raw,
				
				    SplitSubjects =
				        Table.AddColumn (
				            Source,
				            "Transformation",
				            each List.Distinct (
				                List.Transform (
				                    List.Select ( Text.SplitAny ( [Subjects], ", #%;+-" ), each _ <> "" ),
				                    ( x ) => Text.Proper ( Text.Trim ( x ) )
				                )
				            )
				        ),
				
				    CombineList = 
				        List.Combine ( SplitSubjects[Transformation] ),
				
				    Count = 
				        List.TransformMany (
				            List.Distinct ( CombineList ),
				            ( l ) => { List.Count ( List.Select ( CombineList, each _ = l ) ) },
				            ( x, y ) => { x, y }
				        ),
				        
				    Result = 
				        Table.FromRows (
				            List.Sort ( Count, { each _{1}, Order.Descending } ),
				            type table [ Subjects = text, Count = Int64.Type ]
				        )
				in
				    Result
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

